apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: apitest
spec:
  dataFrom:
    - extract:
        key: apitest
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp
  target:
    name: apitest
